import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import Person from '@/components/Person'

//const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)

  function removeData(key) {
    console.log(key);
    delete data[key]
  }

  useEffect(() => {
    setLoading(true)
    fetch('https://63998da716b0fdad77409a5e.mockapi.io/api/v1/hikers')
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
      })
  }, [])



  return (
    <>
      <Head>
        <title>Table overview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.table_container}>
          <div className={styles.header}>
            Attendees ({data ? Object.keys(data).length : 0})
          </div>
          <Person personData={{name:"Name",city:"City",dateOfBirth:"Date of Birth",country: "Country"}} personIndex={null} noExtra={true}/>
          <div className={styles.table_view}>
            {
              data?.map((person,index) => {
                console.log(index);
                return (
                  <Person personData={person} key={index} personIndex={index} removeData={removeData}/>
                )
              })
            }
          </div>
        </div>
      </main>
    </>
  )
}
